### ISSUE TITLE
Something's strange about the way SLM 1.5.0 sees a couple of the "Arcade Archive" titles

### ISSUE THREAD

**Issue by SteveMyers75** [trembon/switch-library-manager#21]
When I scan, it sees "**Arcade Archives BLOCK HOLE[01009E7013B2C000][v0].nsp**" and "**Arcade Archives LIQUID KIDS[01009E7013B2A000][v0].nsp**" as both being **BLOCK HOLE** and says there's a "duplicate base file" ISSUE 
 
I verified that they are actully two completely different games. (One is from TAITO and the other is from KONAMI) 
Both play just fine.

If I delete the file "Arcade Archives BLOCK HOLE[01009E7013B2C000][v0].nsp", the error goes away but it lists **Title:BLOCK HOLE** as using File: **"Arcade Archives LIQUID KIDS[01009E7013B2A000][v0].nsp"**

**Comment by trembon** [comment]
could be an error within the titlesdb file as well, but i will try to have a look at it to see what i can find

**Comment by SteveMyers75** [comment]
I haven't figured out where he fixed it yet, but Pedro's fork fixed this issue.
https://github.com/pedro-dro/switch-library-manager

When I compile his, it works as it should and both titles list properly.

**Comment by SteveMyers75** [comment]
OK, I se where @pedro-dro fixed this issue. 

It's in **db\localSwitchFilesDB.go**

```
			idPrefix := metadata.TitleId[0 : len(metadata.TitleId)-4]				id := metadata.TitleId
			idPrefix := id[0 : len(id)-3]
			if !(strings.HasSuffix(id, "000") || strings.HasSuffix(id, "800")) {
				intVar, _ := strconv.ParseUint(id[len(id)-4:len(id)-3], 16, 64)
				h := fmt.Sprintf("%x", intVar-1)
				idPrefix = id[0:len(id)-4] + h
			}
```

https://github.com/giwty/switch-library-manager/commit/eba1b53c2ec206197c0b9493afec4dd3d04bbbdc  
At line #211 shows the change

**Comment by trembon** [comment]
thanks for the find, either you can create a PR yourself or i will try to merge it when easter is over and i have some time at the computer again

**Comment by trembon** [comment]
i think i have applied all needed code in this code base as well now so you should be able to test with the latest build available under the Actions tab
works for me when testing with this build

**Comment by SteveMyers75** [comment]
That did it, **Thanks!**
Tested and working properly
