### ISSUE TITLE
Extra Space Being Created When Renaming

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [trembon/switch-library-manager#22]
I have the following line in the config for renaming files:
"file_name_template": "{TITLE_NAME} [{TITLE_ID}] [{TYPE}] [{DLC_NAME}] [v{VERSION}] [v{VERSION_TXT}] [{REGION}]"

This results in:
Bayonetta 2 [01007960049A0000]  [v0] [v1.0] [US].nsp
(There are two spaces instead of one between the title id and version)

**Note** The extra space is NOT created when renaming updates or DLC. It ONY happens with the main game nsp and ONLY when both {TYPE} & {DLC_NAME} are used next to each other anywhere in the string.

**Comment by trembon** [comment]
seems like a weird behavior, i will take a look at it when possible

**Comment by harvestry-of-ghosts** [comment]
> seems like a weird behavior, i will take a look at it when possible

Thanks. I have updated the note at the end of the op to better reflect the circumstances in which the extra space is added.

**Comment by trembon** [comment]
at the end of generating the new file name when organizing all double spaces was replaced with a single spaces, but your scenario ends up with 3+ spaces in a row so this only gets fixed half way
it is now fixed so all extra spaces should now get replaced with a single space (you can get the latest build from the Actions tab)

**Comment by harvestry-of-ghosts** [comment]
Thank you. Works great. :)
