### ISSUE TITLE
add titles/version json urls as variables in settings.json

### ISSUE THREAD

**Issue by trembon** [trembon/switch-library-manager#23]
add two new variables in the settings.json and use these instead of the static variables in settings.go

**Comment by harvestry-of-ghosts** [comment]
There was an update to the US.en.json (renamed to titles.json) that fixed Princess Peach icon, info, etc missing. But when I start SLM it overwrites the file I placed there with one without the fix. IN addition to custom url, could you please add the ability to skip downloading and just use the already existing files?

**Comment by trembon** [comment]
available in the latest Actions build and noted in the readme under the Settings section
