### ISSUE TITLE
App opens minimized

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [trembon/switch-library-manager#28]
The app always opens minimized for me on both my desktop and laptop. Giwty release also has this behavior so it's not just this fork. For reference, all other apps on both desktop and laptop open as expected.

**Comment by trembon** [comment]
wasnt able to recreate this problem at first on my end, but i have tried to fix with a bit of a work around

**Comment by harvestry-of-ghosts** [comment]
Seems to have taken care of it. Can mark as fixed. Thank you. :)
