### ISSUE TITLE
Update date sorts by month rather than year

### ISSUE THREAD

**Issue by frank-owen** [trembon/switch-library-manager#29]
When clicking the "update date" header to sort by update date the data sort by month rather than by year, despite being displayed in the correct yyyy-mm-dd format. This results in the items being listed not in chronological order as expected.

(PS Thanks for updating with this fork!)

**Comment by trembon** [comment]
will look into this when i have the time :)

**Comment by trembon** [comment]
sorting was done by date but was parsing the wrong date format, it should be fixed now

will be included in the next release or the latest build under the Actions tab

**Comment by frank-owen** [comment]
Great thanks a lot for your work on this!
