### ISSUE TITLE
Have Organize Files work even when the Base file is not in the Folder being scanned

### ISSUE THREAD

**Issue by SteveMyers75** [trembon/switch-library-manager#30]
It would be great if Organize Files would process a folder even when the Base File is missing.
Right now it just gives a **Base File Missing** error.
This comes up a lot when working with Game Updates and DLC and we need them to be properly renamed before moving them to  Master Backup Folders. 
Latley a lot of Game Updates are just the TitleID and Version with no Title Name attached like:  **[0100ABC123450000][v86753].nsp**
SLM is capable of properly renaming these files, but we have to move the Base file in the same directoty to get it to process.

**Comment by trembon** [comment]
sounds like a good feature to add, will add it to the todo list

**Comment by trembon** [comment]
available in the latest build with the setting "process_when_missing_base_game"

**Comment by trembon** [comment]
released with 1.8.0

**Comment by NikoMuffin** [comment]
I like the idea of this.  @trembon  can I assume Switch library manager will still alert the user of the missing base file?
