### ISSUE TITLE
Error macOS Big Sur 11.7.10

### ISSUE THREAD

**Issue by tsuihak** [trembon/switch-library-manager#31]
I am having a mistake when trying to open the program at MacOS asking to contact the developer.
<img width="293" alt="Captura de Tela 2024-06-18 às 13 05 38" src="https://github.com/trembon/switch-library-manager/assets/23452472/210c91ab-2d1f-4477-b696-bd2db0555d27">

**Comment by trembon** [comment]
do you have any knowledge in how to try and compile this yourself and see if that version works?

i have not access to any mac device and i'm unable to test and try to fix this myself without just guessing.
will see if i can find anything related to this, but i'm tagging this as help wanted as i cant do this myself currently.

**Comment by tsuihak** [comment]
Unfortunately I also have no experience in programming. What I can say is that version 1.4.0 worked perfectly up to firmware prod.keys 16. I got a PC with Windows here and it worked perfectly. I've already managed to improve and update my library.

**Comment by trembon** [comment]
when i started working on this i upgraded a lot of dependencies, so my guess would be that one of them requires a newer macOS version, or the compile process would need to be updated to support the older versions

**Comment by trembon** [comment]
i needed to make a change to the build configuration to mac for other reasons, if you download the latest build under the Action tab here on GitHub, does that build work for you?

**Comment by tsuihak** [comment]
Still got the same error. Thanks for trying to resolve it. Meanwhile I'm using the Windows version. I ended up learning something else from you because I didn't know where to find the version you posted and I discovered it.

**Comment by trembon** [comment]
not sure either, but great that its working now!
