### ISSUE TITLE
If They Do Not Exist, SLM Errors on Trying to Download Versions.Json and Titles.Json

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [trembon/switch-library-manager#35]
When starting SLM prom a pre-existing setup of the app and there are no pre-existing versions.json or titles.json, downloading of both fails with error and produces 0kb files. This only happens with a pre-existing folder. If a fresh empty folder is used and only Switch-Library-Manager.exe and prod.keys are placed in the new folder, the json files download properly as expected. Something going on if the files are deleted from a pre-existing SLM setup folder and you start the app. Edit: Using commit 2217b39 but also tried "Latest" version 1.6.0 with same results.

![Clipboard_07-05-2024_01](https://github.com/trembon/switch-library-manager/assets/13652531/ee49d799-1af2-49d7-8c76-22b035212de9)

**Comment by larg000** [comment]
these error may come from settings.json 

for some reason the definition of variables "versions_json_ur" and "titles_json_url" seem to become empty in file.

**Comment by harvestry-of-ghosts** [comment]
> these error may come from settings.json
> 
> for some reason the definition of variables "versions_json_url" and "titles_json_url" seem to become empty in file.

I deleted the two json files to trigger the error message and then looked at my settings file. The urls are still there for me. Tried to replicate several times, but the urls don't ever become empty for me.

**Comment by trembon** [comment]
i did some updates when reading the settings file regarding verifying that urls and files exists correctly and try to correct them if the settings are in a bad state, hopefully this will resolve some of these errors
