### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mspykerez** [trembon/switch-library-manager#39]
Hey can you merge the changes that [pedro-dro](https://github.com/pedro-dro/switch-library-manager) made? There are some fixes and nice improvements there such as:

> Added "ignore_demos" option in 'settings.json' . All titles with field "isDemo" set to true in "titles.json" are ignored
> Added "blacklist.json" support. If present, all titles/dlc in this file are ignored. Ideal to avoid those games you'll never want in your list. Fields -> "Id" (mandatory), "Name", "Region", "Reason"
> Added "whitelist.json" support. If present, all content included in this file is always listed. Ideal to add cart only games, homebrew or to redefine an already existing title listed in 'titles.json'. File struct the same 'titles.json' but only ID is mandator
> Added TITLEID, REGION and TYPE filter to "LIBRARY" tab
> Added TITLEID and REGION filter to "MISSING GAMES" tab
> Added TITLEID filter to "MISSING DLC" tab
> Added direct access to file update if exists. Just press CONTROL key on keyboard and then click on UPDATE or VERSION value
> New export method in MISSING DLC tab. Now creates a row for every missing dlc. The old method is also kept but has been renamed to "export to CSV (compact)"

The filters are great to have! However I wish they could be smarter. Ex: for the game ‘’Super Mario 3D World’’ if you write ‘mario world’ on the filter it will not pick up anything but if you write ‘3d world’ it will show.

The dates on the MISSING GAMES tab needs a fix because they are displayed without spaces between the numbers (unlike the dates on the MISSSING UPDATES tab) making it a bit confusing to read.
Also I don't know if you can add 2 COLUMNS in MISSING GAMES for #number of DLCs available (if any) plus if it has an update available (y/n).

The library is also missing a release date column.

In addition having some extra COLUMNS would be nice:
-Languages
-Publisher
-Developer
-Genre
-Size
-Firmware
-Description of the game (because this can be long, perhaps make it a popup when clicked with screenshots and everything)

Could also add the ability to enlarge the current thumbnails.

I know that all this data can be retrieval because good old [NSC_BUILDER](https://github.com/julesontheroad/NSC_BUILDER) does it when scanning the games i think.

Finally can we have a dark mode ?

**Comment by trembon** [comment]
all these changes are to much for one issue and would need to be broken down in one issue per requested change, but i'll answer some of the things here and then keep it up for a while before i close this issue, but separate issues will be created when working on something from this list

> Hey can you merge the changes that [pedro-dro](https://github.com/pedro-dro/switch-library-manager) made? There are some fixes and nice improvements there such as

are all of them relevant? if you know your way around code, you are more then welcome to lift some of the changes over as a PR

> The filters are great to have! However I wish they could be smarter. Ex: for the game ‘’Super Mario 3D World’’ if you write ‘mario world’ on the filter it will not pick up anything but if you write ‘3d world’ it will show.

this is based on a already existing component and i'm not sure this is possible without a lot of changes

> Also I don't know if you can add 2 COLUMNS in MISSING GAMES for #number of DLCs available (if any) plus if it has an update available (y/n)

the data is there, just not sure if it would performance wise to make this lookup for all games, as there are a lot of them in this list, but i might be able to look into it to see if its possible

> In addition having some extra COLUMNS would be nice

yes, as you stated, all of these fields would be to much to have in the table, so a popup seems like a more real solution for this

> Finally can we have a dark mode

the app wasnt really prepared for this functionallity, so it is possible, but will require some work to have working

**Comment by mspykerez** [comment]
Unfortunately i'm no coder.

btw should i create a new issue for each request in here or you add to the todo list what you can implement?

**Comment by trembon** [comment]
that would be optimal, yes
to keep track of code mapped to discussions they need to be as separate issues
otherwise i will create new issues when i start working on them
but keeping them separate will help me not forget items and it will also help others to see what is already requested or are known issues, both for normal users and other developers to let them show whats available to work with if they would like to help

**Comment by trembon** [comment]
created some new issues from this, so closing this one now
