### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by mspykerez** [trembon/switch-library-manager#40]
So on the ISSUES tab can we have an option to ignore the ‘file type is not supported’ from being listed there because - and speaking for myself - depending on the directory that the app scans it can become super bloated making it harder to keep track of other issues.

Also there are game files that can be 'multicontent' (mostly physical releases) which means that the file already has an update or DLC bundled together with the base game.
What I notice is that sometimes the update or DLC that comes attached with these multicontent files can become outdated and SLM reports it as an issue: ''old update file, newer update exist locally''
I think there should be an option to ignore this issue because you wouldn't want to get rid of the multicontent file because the base game can be there and surely want to avoid getting it deleted by SLM when organizing with the option ''Delete old update files'' set to true. tbh don't know if SLM has any checks in place to make sure that this doesn't happen or not.

**Comment by trembon** [comment]
first one is now #42 

the second part i dont know i much work it will be and i dont think its something that i will time to look into in the near future, but will create it as an improvement if i start to look into it

closing this as it is multiple improvements in the same issue
