### ISSUE TITLE
fix release date format on missing games

### ISSUE THREAD

**Issue by trembon** [trembon/switch-library-manager#46]
displayed without dashes which makes it harder to read

**Comment by larg000** [comment]
can you explain how to download new build ?
why dont you provide new release ?

**Comment by trembon** [comment]
@larg000 its under the Action tab here on GitHub, then select the latest build and the files are there
reason for this is that i havent had much time at the computer this summer due to having the kids home for a long period of times and the plan was to fix some more bugs and maybe add a feature before a new release

**Comment by trembon** [comment]
fixed with release 1.7.0
