### ISSUE TITLE
add option to hide demo games

### ISSUE THREAD

**Issue by trembon** [trembon/switch-library-manager#48]
example  "ignore_demos"  in settings.json

**Comment by NikoMuffin** [comment]
Would love this

**Comment by trembon** [comment]
available in the latest build with the setting "hide_demo_games"

**Comment by r3nfolly** [comment]
When I enable the hide_demo_games and reload the app, the option is removed from the config file.

**Comment by trembon** [comment]
have you downloaded the latest build from the Actions tab here on GitHub?
under the release tab and release 1.7.0 does not contain this change

**Comment by r3nfolly** [comment]
I see. I was trying on the 1.7.0. Thanks for the help trembon.

**Comment by trembon** [comment]
released with 1.8.0
