### ISSUE TITLE
add ability to hide specific Missing Updates by title ID

### ISSUE THREAD

**Issue by one1111111111** [trembon/switch-library-manager#49]
Hi,

I was wondering if there is a way to add specific title ID's to be ignored on the 'Missing Updates' tab? There are some for Civ VI that don't seem to exist that I can find. I've also used the NSX Library manager and they do not show up there as being missing. I much prefer this library manager over NSX. 

Thanks in advance! :)
![civ6UpdatesMissing](https://github.com/user-attachments/assets/5b868354-6935-465e-976c-694efce6af5c)

**Comment by trembon** [comment]
it would be possible to hide these using the setting `ignore_dlc_updates` with `true`
otherwise the solution would be to add a solution to updates that works the same way as the `ignore_dlc_title_ids` setting

**Comment by one1111111111** [comment]
Ok thank you. yea i don't want to ignore all title updates, just these specific ones.

**Comment by trembon** [comment]
i will tag it as an enhancement then :)

**Comment by one1111111111** [comment]
You rock, thank you so much!

**Comment by trembon** [comment]
fixed with release 1.7.0

**Comment by one1111111111** [comment]
You are awesome bro!

**Comment by xadox-1st** [comment]
How should the IDs be entered into the settings file?
Tried several think, but then the application will not start anymore.
