### ISSUE TITLE
DLC name not being renamed into file

### ISSUE THREAD

**Issue by u4113057** [trembon/switch-library-manager#56]
![switch dlc](https://github.com/user-attachments/assets/52533055-5c55-44b1-82ab-9a13d1d328d3)
switch dlc when rename is not include the dlc name 
i use the default pattern from json
  "file_name_template": "{TITLE_NAME} ({DLC_NAME})[{TITLE_ID}][v{VERSION}]"

**Comment by Golumpa** [comment]
This renamed fine for me, you might have old titles as tinfoil stopped serving titles.json not long ago.

As a work around you can build your own titles.json using nut
or
download ownfoil's lang build, choose the lang you want, rename it to titles.json and replace the one inside the switch-library-manager folder

https://nightly.link/a1ex4/ownfoil/workflows/region_titles/master/titledb.zip

**Comment by larg000** [comment]
Works fine for me 
i use this :
{TITLE_NAME} [{TYPE}] {DLC_NAME} [{TITLE_ID}][v{VERSION}]

and think this could be a fine default value

**Comment by trembon** [comment]
closing due to no response
