### ISSUE TITLE
[reason: failed to read NCA header EOF]

### ISSUE THREAD

**Issue by r3nfolly** [trembon/switch-library-manager#60]
Some files get this error, do you know what it is?

[reason: failed to read NCA header EOF]

**Comment by trembon** [comment]
EOF normally means ends of file and looking at the code this error is before trying to read the file using the prod.keys, are you sure the files trying to be read contains data or are correct NSP/NSZ/XCI files?

**Comment by r3nfolly** [comment]
Yes, 

METAL GEAR SOLID\METAL GEAR SOLID (Master Collection Version Japanese Language Pack)[010033301A9C1001][v0].nspfailed to read NSP [reason: failed to read NCA header EOF]

NBA 2K25\v-nba_2k25_v65536.nspfailed to read NSP [reason: failed to read NCA header EOF]

Only these to files get this error, I tried to download them again from different sources, but the error continues.

**Comment by trembon** [comment]
they might have an updated structure, will see if i can reproduce this on my end and see if i can find anything that can be changed to fix this

**Comment by Buzbee** [comment]
METAL GEAR SOLID\METAL GEAR SOLID (Master Collection Version Japanese Language Pack)[010033301A9C1001][v0].nsp is a known bad dump on all sites.

**Comment by trembon** [comment]
looking at the v-nba_2k25_v65536.nsp file, it does look like bad dump as well
the metadata file inside the nsp file is at position 54661637008, which would indicate the file is 54gb, which it not and is why its failing by trying to access this position which does not exist
so either they changed something in how data is stored in the nsp file, or it is a bad dump as well (or atleast what i can see now)

**Comment by trembon** [comment]
reading on other places there are a lot of people having problem with this game and its update, i dont think there is anything i can do here for now

**Comment by r3nfolly** [comment]
Yes, I'll close this one, Thanks Trembon
