### ISSUE TITLE
minor bug with specials characters and japenese characters

### ISSUE THREAD

**Issue by larg000** [trembon/switch-library-manager#62]
minor bug with special character and japonese characters

i have 2 games in mind :
Bō: Path of the Teal Lotus and DoDonPachi (in dont remember if this is Resurrection or Re:Incarnation)

example :
display looks ok in library but icon and name dont show correctly in missing update

same kind of bug with some games that could have japonese character in title

**Comment by trembon** [comment]
i have no problem viewing them under missing games on my end, will see if i have the possibility to test them

**Comment by larg000** [comment]
note that it dont happen in all tabs.
for a particular game in some some tabs text and icon are ok and in an other tab icon or text is missing
also my windows is not configured english native maybe this could affect the characters list used by the system.

**Comment by trembon** [comment]
> also my windows is not configured english native maybe this could affect the characters list used by the system.

that could be the reason, either that or the data read from the game files are handled differently

**Comment by larg000** [comment]
for "**Bō**: Path of the Teal Lotus" (0100E0601DC2A000) :
created directory is "**B** : Path of the Teal Lotus" 
o with special character is missing
and cause of this little bug, the game appear in "missing games" tab, that it shouldnt

japanese games are referenced with their japanese name in switch-library 
but directory are created with english name
i think a choice should be made 
all english or all japonese but not a mix

problem with DoDonPachi Blissful Death Re:Incarnation (0100526017B00000):
created directory and file name are "1.0.0"
due to blawar db ?

finally "title id" column is lowercase on first tab "library" but uppercase on other tabs

**Comment by larg000** [comment]
thx for the futur fix

**Comment by trembon** [comment]
a fix for naming the "Bō: Path of the Teal Lotus" is in the latest build under the Action tab now

not really sure how it should be possible to handle the japanese characters for other games

**Comment by trembon** [comment]
fixable part is in the 1.9.0 release
