### ISSUE TITLE
Organize dlc/updates in separate folders with create_folder_per_game as false

### ISSUE THREAD

**Issue by benspray** [trembon/switch-library-manager#64]
Hi thanks for the great work here ;)

As per SteveMyers75 question on issue 55 I'd also like the ability to organize files in that way, ie

x:\switch (all base games in one folder, this is the only way I can get playnite to correctly scan)
    x:\switch\updates (subfolder under base for all games updates)
    x:\switch\DLC (subfolder under DLC for all games updates)

Perhaps having the create_folder_per_game to false and then setting paths for the DLC/updates would make it behave this way, and having  create_folder_per_game to true leaves it behaving in the current way with DLC and updates under a per game folder?

The issue with per game subfolders or having all updates and DLC in one base folder causes playnite to scan everything as a game so you get multiple entries for all the updates/dlc etc, with the games in one folder then the updates etc stored away in subfolders the scanning on playnite ignores them.

Thanks :)

**Comment by benspray** [comment]
Nice one thanks ;)

**Comment by trembon** [comment]
available in the latest beta build under the Actions tab here on GitHub

**Comment by benspray** [comment]
Cool thanks, appears to work however will wait until the issue of seeing xcis with updates in them as updates is fixed also, as these are moved to the update folder as well at the mo 👍

**Comment by trembon** [comment]
i havent been able to get my hands on a multi-content file yet, so i'm yet to work on that one

**Comment by benspray** [comment]
no worries, it's actually fine using this new feature then just manually moving those files back, thanks :)

**Comment by trembon** [comment]
the multi-content problem should be fixes in the latest beta build now :)

**Comment by benspray** [comment]
Cool thanks will check it out later today

**Comment by benspray** [comment]
cheers, looking good mostly as per comment on the other thread :)

**Comment by trembon** [comment]
feature is included in the 1.9.0 release
