### ISSUE TITLE
incorrect metadata when organizing multi-content files

### ISSUE THREAD

**Issue by Halofan240** [trembon/switch-library-manager#66]
Games that have the updates and dlc combine with them show up as update when organizing with the updates and dlc folder active.

Example below is breath of the wild xci that has the updates and dlc added to it. So, it shows up as multi-content. But when organized it ends up in the updates folder which you can see in the file path. Despite the fact it's not an update. Also when using {TYPE} it will show up with a UDP added to it.

<img width="940" alt="image" src="https://github.com/user-attachments/assets/a10d3c26-d3cd-4be9-ad4f-cfac1ad4fa7b">

**Comment by benspray** [comment]
also seeing this, seems if you organise again it will rename back to v0 and remove the UPD tag, seems to flip between marking as base and marking as update each time you organise

**Comment by Halofan240** [comment]
Same with me on this too.

**Comment by trembon** [comment]
fix should be available in the latest beta build under the Actions tab here on GitHub

**Comment by benspray** [comment]
mostly working, still have a few files that get renamed as updates and move to subfolders ;) may be due to the fact that either they also have DLC or that they are "old updates" in the issues tab shows newer updates are in other nsp files so maybe the app doesnt know what to do with these

**Comment by trembon** [comment]
@benspray do you know what those multi-content contain? if its only dlcs and updates, the manager wont know what to do with the files

**Comment by benspray** [comment]
Hi, they include base,dlc and update the only difference I can see from working ones are that I have newer/duplicate updates in separate files (which are working ok)
I'll try deleting the newer/duplicate update files and see if that helps 👍

**Comment by benspray** [comment]
I think that sorts it, if you have a "duplicate" ie a multipart xci with updates and dlc and then an nsp with maybe a newer update, it will rename the xci as an update and move it to the subfolder. if you remove all of the other nsp files and rescan it will then see it as base and rename properly (but you have to manually move it back out of the updates folder).
As soon as you drop one of the other "duplicate" nsp files in it breaks the xci again by renaming and moving it as an update.
Not sure what the fix would be here?
Cheers

**Comment by trembon** [comment]
i tried with the following setup
base game + old update in a .xci file
new update in .nsp file
2 separate dlcs in .nsp files

i have no problem when trying to organizing these file and i have no scenario where the multi-content file is placed wrongly, do i understand your file setup wrong?

**Comment by benspray** [comment]
Hi, no that sounds exactly right, maybe just something odd about a few files, it only happens on 3 or 4 files, I may be best just to replace/redump the ones with issues 👍

**Comment by trembon** [comment]
fix is included in the 1.9.0 release

**Comment by NikoMuffin** [comment]
@trembon  is my issue #81 related to this issue?

**Comment by trembon** [comment]
@NikoMuffin if i understand it correctly, no, this is not related as this was just how the files should be sorted and not be named
