### ISSUE TITLE
Show both file locations of e.g. duplicate base file / updates / dlc etc.

### ISSUE THREAD

**Issue by grimson73** [trembon/switch-library-manager#69]
Hi, again a feature request:

As I sometimes have multiple or superseded base dlc or update files SLM does notify me which is a nice feature.
SLM does only shows one location where to find this duplicate file, but I would also like to know the location of the other file.

So is it possible to show both locations of the found conflict files so that I can manually scan both locations on where the update should reside?

**Comment by trembon** [comment]
depending on how its setup, this might be an easy fix or it will require some work, but will tag as an enchancement

**Comment by trembon** [comment]
available in the latest beta build under the Actions tab here on GitHub

**Comment by grimson73** [comment]
> available in the latest beta build under the Actions tab here on GitHub

Super .. many thanks!
It does help a lot to scavenge duplicates when both paths are shown. Yes, I have scattered my dumps sorry.

Shows both filepaths:
duplicate base file.
duplicate update file

Shows only one filepath:
Old update file, newer update exist locally
Old DLC file, newer version exist locally

So .. uhm would it be possible also to include the last two mentioned with both paths in the results?

**Comment by trembon** [comment]
thats handled as a separate case, should just be to copy the code added for the first case, hopefully :)

**Comment by trembon** [comment]
updated with the old update/dlc file scenario as well
