### ISSUE TITLE
This fork forces GUI = true? in settings.json on every run

### ISSUE THREAD

**Issue by 2600box** [trembon/switch-library-manager#7]
Hello,

I saw you had made a number of welcome updates with your fork, and I am grateful. I wanted to give it a go, but I do not use the GUI. So I built the linux binaries which is all good.

When I run the fork, it creates the `settings.json` as usual. Normally I would set `"gui": false,` but every time I run your fork, it resets that variable to `"gui": true,` and it fails to run because I don't have an X environment. 

The rest of the settings.json remains according to my configuration...

Any ideas how this can be resolved?

Thanks!

**Comment by trembon** [comment]
@2600box found an old debug flag to force the GUI in code, removed this in a now merged PR, can you test if this works for you or if this needs more work?

**Comment by 2600box** [comment]
Works great. Thank you!
