### ISSUE TITLE
Crash after starting organization in v1.8.0

### ISSUE THREAD

**Issue by xadox-1st** [trembon/switch-library-manager#70]
v1.8.0 is crashing for me after starting organization. NSX, XCI files are on a SMB Share:

> {
>  "versions_json_url": "https://raw.githubusercontent.com/blawar/titledb/master/versions.json",
>  "versions_etag": "W/\"132bbcb0ae6ffaefdd06137e54b69df68a5cf781fa0794f46d2c7f28fcdfda5f\"",
>  "titles_json_url": "https://tinfoil.media/repo/db/titles.json",
>  "titles_etag": "W/\"7e4bc4ad2fdb1:0\"",
>  "prod_keys": "",
>  "folder": "\\\\smb\\path\\",
>  "scan_folders": [],
>  "gui": true,
>  "debug": false,
>  "check_for_missing_updates": true,
>  "check_for_missing_dlc": true,
>  "hide_missing_games": true,
>  "hide_demo_games": true,
>  "organize_options": {
>   "create_folder_per_game": false,
>   "dlc_folder": "",
>   "updates_folder": "",
>   "rename_files": true,
>   "delete_empty_folders": false,
>   "delete_old_update_files": true,
>   "folder_name_template": "{TITLE_NAME}",
>   "switch_safe_file_names": true,
>   "file_name_template": "{TITLE_NAME} ({DLC_NAME})[{TITLE_ID}][v{VERSION}]",
>   "process_when_missing_base_game": false
>  },
>  "scan_recursively": true,
>  "gui_page_size": 100,
>  "ignore_dlc_updates": false,
>  "ignore_dlc_title_ids": [],
>  "ignore_update_title_ids": [],
>  "ignore_file_types": []
> }

If starting from cmd:

![image](https://github.com/user-attachments/assets/5fb10c89-20fc-4cb1-ba5d-f0f952e81056)

**Comment by trembon** [comment]
as you seem to use a smb share it might share the root cause with #61

**Comment by xadox-1st** [comment]
Tested with a windows mapped SMB share, same issue.

**Comment by trembon** [comment]
i'm using the same and i'm not able to reproduce this error, so its a bit hard for me to debug currently, but will see if i can find anything

**Comment by xadox-1st** [comment]
Are you using the same settings as I am using in the json?

**Comment by trembon** [comment]
will try and see if it makes a difference

**Comment by trembon** [comment]
if you know your way around you could try and see if you can find anything, otherwise i dont really know for now, i will try a bit more to see if i can recreate the problem

**Comment by orangewhipster** [comment]
I am having the very same issue...it will run briefly and then just crash. Same settings as OP...using a mapped "X" drive to network address.

**Comment by trembon** [comment]
thanks for reporting back and helping with this, i'm still unable to recreate this problem.
with my own digging it doesnt seem be related to a SMB share, but rather a memory leak problem

so next step i guess will be to start going through each changed row between 1.7 and 1.8

but how large are you libraries if you are willing to share? ex: X files and X gb

**Comment by trembon** [comment]
@xadox-1st does your library work without this file otherwise?

if that is the cause, i think i know what is broken and that is that the change between 1.7 and 1.8 broke homebrew games that does not exist in the titles.json
will work on a fix for that asap

**Comment by trembon** [comment]
restored support for homebrew files, so hopefully this build should work now: https://github.com/trembon/switch-library-manager/actions/runs/11162189381

**Comment by orangewhipster** [comment]
That fixed it for me too! Awesome! Thanks for the quick work!

**Comment by trembon** [comment]
fix is included in the 1.9.0 release
