### ISSUE TITLE
failed to read NSP [reason: missing Key_area_key[key_area_key_application_10]]

### ISSUE THREAD

**Issue by Seroczynski** [trembon/switch-library-manager#71]
So I know this has been covered before and even discussed in #50 - but in that issue no real solution is given.

I have my prod.keys configured, but there is no _10 and _11, the latest file counts in hexidecimal. So it's now something like:

```
key_area_key_application_09
key_area_key_application_0a
key_area_key_application_0b
key_area_key_application_0c
key_area_key_application_0d
````

**Comment by Jacksoft** [comment]
You have to extract updates keys from your switch with the latest supported fw (18.1.0 actually) and the very latest lockpick rcm (hard to find around).

**Comment by Seroczynski** [comment]
> You have to extract updates keys from your switch with the latest supported fw (18.1.0 actually) and the very latest lockpick rcm (hard to find around).

I have extracted my keys with Lockpick_RCM from 18.1.0.

**Comment by trembon** [comment]
not related to SLM unfortunately, i normally just download my prod.keys by googling and they contain the key_area_key_application_10 and key_area_key_application_11 items
